### ISSUE TITLE
Tiddly Dark on windows 11

### ISSUE THREAD

**Issue by AnthonyMuscio** [ahanniga/tiddly-dark-desktop#1]
Hi, This interests me I so I have attempted to install and run on my desktop;

Unfortunately when I try to execute I am getting the following dialogues
* I tried remove spaces in the paths as a hunch but no success.
* Do we need to install electron or some other dependency and how do we do it please?
 
![Snag_7d84d](https://user-images.githubusercontent.com/31584658/175753682-daa50c61-54f7-47cf-a980-7093814290ad.png)

**Comment by ahanniga** [comment]
Hi, from the message above I think you may have downloaded the source, not the release? The release contains all the dependencies. Can you confirm you extracted (unzipped) all the files and directories from the Win32 version from the [Releases](https://github.com/ahanniga/tiddly-dark-desktop/releases) page?

Once all the files are extracted, you can rename the "Tiddly Dark-win32-x64" directory to "Tiddly-Dark" and move it into C:\data.

**Comment by AnthonyMuscio** [comment]
I tried again and don't have the problem now. Now I can play and provide some feedback but I must say it is looking great. Not only as a solution but as a deployment method.

Thank you

**Comment by AnthonyMuscio** [comment]
Thus closed thanks
